export const SEATS_LIST_REQUEST = 'SEATS_LIST_REQUEST';
export const SEATS_LIST_SUCCESS = 'SEATS_LIST_SUCCESS';
export const SEATS_LIST_FAIL = 'SEATS_LIST_FAIL';

export const CONVERT_SEATS_REQUEST = 'CONVERT_SEATS_REQUEST';
export const CONVERT_SEATS_SUCCESS = 'CONVERT_SEATS_SUCCESS';
export const CONVERT_SEATS = 'CONVERT_SEATS';